--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/CoinAPI
build-by-default: true
branches:
- master
projects:
  CoinAPI:
    path: ""
  libCoinAPI:
    model: virion
    type: library
...
